import { ModuleMetadata, Type } from '@nestjs/common';

/** Configuration options for `StorageModule.forRoot()`. */
export interface StorageModuleOptions {
  /** Project API key used in the `X-API-Key` header. */
  apiKey: string;
  /** Base URL of the storage server (e.g. `https://storage.wiicode.org`). */
  storageEndpoint: string;
}

/** Factory interface for providing storage options via a class. */
export interface StorageModuleOptionsFactory {
  createStorageOptions():
    | StorageModuleOptions
    | Promise<StorageModuleOptions>;
}

/** Async configuration options for `StorageModule.forRootAsync()`. */
export interface StorageModuleAsyncOptions
  extends Pick<ModuleMetadata, 'imports'> {
  /** Factory function that returns module options. */
  useFactory?: (
    ...args: any[]
  ) => StorageModuleOptions | Promise<StorageModuleOptions>;
  /** Providers to inject into `useFactory`. */
  inject?: any[];
  /** Class that implements `StorageModuleOptionsFactory`. Will be instantiated by the module. */
  useClass?: Type<StorageModuleOptionsFactory>;
  /** Existing provider that implements `StorageModuleOptionsFactory`. */
  useExisting?: Type<StorageModuleOptionsFactory>;
}

/** Metadata returned for a successfully uploaded file. */
export interface UploadedFile {
  /** Original file name as provided by the client. */
  originalName: string;
  /** Unique timestamped name generated by the server. */
  generatedName: string;
  /** Relative storage path on the server. */
  path: string;
  /** Full public URL to access the file. */
  url: string;
}

/** Raw response shape from `POST /api/upload`. */
export interface UploadResponse {
  file: UploadedFile;
}

/** Raw response shape from `POST /api/upload-multiple`. */
export interface UploadMultipleResponse {
  files: UploadedFile[];
}

/** Options for server-side image compression. */
export interface CompressOptions {
  /** Compression quality from 1 (lowest) to 100 (highest). Default: `80`. */
  quality?: number;
  /** Maximum image width in pixels (minimum: 100). Default: `2000`. */
  maxWidth?: number;
  /** Maximum image height in pixels (minimum: 100). Default: `2000`. */
  maxHeight?: number;
}

/** Metadata for an uploaded file that was compressed server-side. */
export interface CompressedFile extends UploadedFile {
  /** Whether compression was applied. */
  compressed: boolean;
  /** Resulting width in pixels after compression. */
  width?: number;
  /** Resulting height in pixels after compression. */
  height?: number;
}

/** Raw response shape from `POST /api/upload-multiple-compressed`. */
export interface UploadMultipleCompressedResponse {
  files: CompressedFile[];
}

/** Response from `DELETE /api/files`. */
export interface DeleteResponse {
  /** Confirmation message from the server. */
  message: string;
}

/**
 * Describes a file to upload. Compatible with `Express.Multer.File`.
 */
export interface FileInput {
  /** File contents as a Buffer. */
  buffer: Buffer;
  /** Original file name from the client. */
  originalname: string;
  /** MIME type (e.g. `image/png`). Optional but recommended. */
  mimetype?: string;
}
